config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'matches/new'

  root 'pages#home'

  resources :players
  resources :matches

  get '*path' => redirect('/')
end

app/models/match.rb
class Match < ActiveRecord::Base
  validates :loserscore, :winner_player_id, :loser_player_id, :date, presence: true;
  validates :loserscore, inclusion: { in: 1..9 }
  validate :no_match_with_himself

  def no_match_with_himself
    if winner_player_id == loser_player_id
      errors.add(:match, "can't be between the same player")
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :nickname, presence: true, uniqueness: true, length: { minimum: 2, maximum: 30};
  validates :firstname, :lastname, presence: true, length: { minimum: 2, maximum: 30};
  has_attached_file :avatar, 
                    styles: { :medium => "150x150>" },
                    default_url: "default_:style.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def full_name
    "#{firstname} #{lastname} (#{nickname})"
  end

  def wins
    Match.where(winner_player_id: self.id) 
  end

  def losts
    Match.where(loser_player_id: id)
  end

  def number_of_wins
    wins.count
  end

  def number_of_losts
    losts.count
  end

  def number_of_matches
    wins.count + losts.count
  end

  def points_earned
    @points = wins.count * 10
    losts.each do |lost|
      @points = @points + lost.loserscore
    end
    @points
  end

  def points_lost
    @points = losts.count * 10
    wins.each do |win|
      @points = @points + win.loserscore
    end
    @points
  end

  def simple_rank_points
    number_of_wins * 1 - number_of_losts * 0.3 + points_earned/10 * 0.1 - points_lost/10 * 0.1 
  end

  def self.simple_rank(players)
    players.to_a.delete_if { |player| player.number_of_matches == 0 }
  end

  def update_rank
    self.rank = simple_rank_points.round(2)
    self.save
  end

  def self.update_position
    @players = Player.all
    @players = Player.simple_rank(@players)
    @players = @players.sort_by { |player| player.rank.to_f }.reverse

    @players.each_with_index do |player, index|
      player.position = index + 1
      player.save
    end
  end

  def self.top_players
    @players = Player.all.order(:position)
    @players = Player.simple_rank(@players)
    @top_players = []
    if @players.count > 3
      @top_players.concat([@players[0], @players[1], @players[2], @players[3]])
    end
    @top_players
  end

  def self.top_player
    @players = Player.all.order(:position)
    @players = Player.simple_rank(@players)
    @players[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      @winner = Player.find(params[:match][:winner_player_id])
      @winner.update_rank
      @loser = Player.find(params[:match][:loser_player_id])
      @loser.update_rank
      Player.update_position
      flash[:success] = "Match created"
      redirect_to @match
    else
      render 'new'
    end
  end

  def show
    begin
      @match = Match.find(params[:id])
      @winner = Player.find(@match.winner_player_id)
      @loser = Player.find(@match.loser_player_id)
    rescue ActiveRecord::RecordNotFound => e
      render 'error'
    end    
  end

  def error
  end

  private

    def match_params
      params.require(:match).permit(:loserscore, :winner_player_id, :loser_player_id, :date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @top_players = Player.top_players
  end

  def about
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @players = Player.order(sort_column + " " + sort_direction)
    @players = Player.simple_rank(@players)
  end

  def show
    begin
      @player = Player.find(params[:id])
      @wins = @player.wins.order("date DESC")
      @losts = @player.losts.order("date DESC")
    rescue ActiveRecord::RecordNotFound => e
      render 'error'
    end
  end

  def new
    @player = Player.new
  end

  def create
    begin
      @player = Player.new(player_params)
      @player.rank = 0
      if @player.save
        flash[:success] = "Player created"
      end
      redirect_to player_path(@player)
    rescue
      render 'new'
    end
  end

  def edit
    begin
      @player = Player.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      render 'error'
    end
  end

  def update
    @player = Player.find(params[:id])
    begin
      @player.update_attributes(player_params_avatar)
      flash[:success] = "Avatar updated"
      redirect_to player_path(@player)
    rescue ActionController::ParameterMissing => e
      flash[:danger] = "First choose avatar file"
      redirect_to :back
    end
  end

  private

    def player_params
      params.require(:player).permit(:firstname, :lastname, :nickname, :avatar)
    end

    def player_params_avatar
      params.require(:player).permit(:avatar)
    end

    def sort_column
      Player.column_names.include?(params[:sort]) ? params[:sort] : "position"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "desc" ? "asc" : "desc"
    link_to title, {sort: column, direction: direction}, class: css_class
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
<% end %> 

app/views/layouts/_navigation.html.erb
    <nav class="col-sm-2"><!--nav-->
      <div class="row">
        <ul class="nav nav-pills nav-stacked">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Ranking", players_path %></li>
          <li><%= link_to "Add Player", new_player_path %></li>
          <li><%= link_to "Add Match", new_match_path %></li>
          <li><%= link_to "About", pages_about_path %></li>          
        </ul>        
      </div>
    </nav><!--/nav-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> - FoosballTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  
  <div class="row">
    <%= render 'layouts/navigation' %>      
      <div class="col-sm-10"><!--content-->
        <div class="row">
          <div class="col-xs-12">            
            <div class="row">
              <div class="col-sm-10"><!--content-->
                <%= render 'layouts/messages' %>
                <%= yield %>
              </div>
            </div>  
          </div>
        </div>
      </div>
    </div>   
        
 </div><!--/content-->

    <footer class="row footer">
      <div class="panel-footer"><p>&copy; 2015 Jan Mrowiec</p></div>
    </footer>
    <%= debug(params) if Rails.env.development? %>



</body>
</html>

app/views/matches/error.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>We have the problem</h1>
    <p>
      This match doesn't exist!
    </p>
  </div>
</div>

app/views/matches/new.html.erb
<% provide(:title, "Add new match") %>
<h1>Add new match</h1>
<div class="row">
  <div class="col-sm-4">
    <% if Player.count > 1 %>
      <%= form_for @match do |f| %>
        <%= render '/shared/error_messages', object: f.object %>
        <%= f.label :winner_player_id, "Winner: " %>
        <%= f.collection_select :winner_player_id, Player.all, :id, :full_name, {}, html_options = { class: "form-control" } %><br>
        <%= f.label :loser_player_id, "Loser: " %>
        <%= f.collection_select :loser_player_id, Player.all, :id, :full_name, {}, html_options = { class: "form-control" } %><br>
        <%= f.label "Loser's score" %>
        <%= f.select :loserscore, options_for_select(1..9), {}, { class: "form-control" } %><br>
        <%= f.label "Match date (click to open calendar)" %>
        <%= f.text_field :date, class: "form-control" %><br>
        <%= f.submit "Add match", class: "btn btn-default" %>
      <% end %>
    <% else %>
    <div class="row">
      <div class="col-md-12">
        <h2>Upss. We have a problem</h2>
        <p>You must add at least two players before you add a match!</p>  
        <%= link_to "Add player", new_player_path, class: "btn btn-default" %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col-sm-6">
    <%= image_tag("match.jpg") %>
  </div>
</div>

app/views/matches/show.html.erb
<% provide(:title, "Match #" + @match.id.to_s ) %>
<h3>This is match #<%= @match.id %></h3>
<p>Match played <b><%= @match.date %></b></p>

<div class="row">

  <div class="col-sm-4">
    <h3>Winner</h3>
    <p id="winner"><%= @winner.firstname + " " + @winner.lastname %><br>
    (<%= @winner.nickname %>)</p>
    <%= image_tag @winner.avatar.url(:medium) %>
    <p><b>Score: 10</b></p> 
    <%= link_to "Go to winner page", player_path(@winner), class: "btn btn-default" %>
  </div>

  <div class="col-sm-4">
    <h3>Loser</h3>
    <p id="loser"><%= @loser.firstname + " " + @loser.lastname %><br>
    (<%= @loser.nickname %>)</p>
    <%= image_tag @loser.avatar.url(:medium) %>
    <p><b>Score: <%= @match.loserscore %></b></p>
    <%= link_to "Go to loser page", player_path(@loser), class: "btn btn-default" %>
    </div>

  <div class="col-sm-4">
    <%= column_chart({ "Winner" => 10, "Loser" => @match.loserscore }) %>
  </div>

</div>
<p></p>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<div class="row">
<div class="col-md-12"><!--content-->
  <h1>Hello, I am Jan</h1>
  <p>This is my Foosbal Tracker - the app made for the Lunar Logic internship.</p>
  <p>Below you can find some of the featured I implemented: </p>
  <div class="col-md-8">
    <ul>
    <li>Fourth best player on the home page + chart</li>
    <li>Ranking - you can sort by position/name</li>
    <li>Player page - some stats and charts and all his matches sorting by date</li>
    <li>Adding match - for date I used DatePicker</li>
    </ul>
    <p>I prepared seed.rb file. So run <b>rake db:seed</b> to make some real-world data.</p>
  </div>
</div>
</div>

app/views/pages/home.html.erb
      <% provide(:title, "Home") %>
      <div class="row">
        <div class="col-md-12">
          <h1>Hello!</h1><p class="lead">Welcome to Foosbal Tracker. What do you want to do?</p>
          <div class="row">
            <div class="col-md-9 col-md-push-3"><%= link_to "New player", new_player_path, class: "btn btn-default" %></div>
            <div class="col-md-3 col-md-pull-9"><%= link_to "New match", new_match_path, class: "btn btn-default" %></div>
            <div class="col-md-3 col-sm-6 post"></div>
        </div>
      </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2>Currently 4 best players</h2>
            <% if !@top_players.empty? %>
              <%= column_chart({ 
                              @top_players[0].nickname => @top_players[0].rank,
                              @top_players[1].nickname => @top_players[1].rank,
                              @top_players[2].nickname => @top_players[2].rank,
                              @top_players[3].nickname => @top_players[3].rank
                              }) %>
            <% end %>
        </div>
          <% if !@top_players.empty? %>
            <% @top_players.each do |top_player| %>
            <div class="col-md-3 col-sm-6 post">
              <%= link_to image_tag(top_player.avatar.url(:medium)), player_path(top_player), class: "thumbnail", id: top_player.nickname %>
              <h2><%= top_player.firstname + " " + top_player.lastname %></h2>
              <p>Also called @<%= top_player.nickname %>.</p>
            </div>
            <% end %>
          <% else %>
            <div class="col-md-12">
              <p>There are no top players yet! Reason is simple: there aren't at least four players who have played their first match.</p>
            </div>            
          <% end %>
        </div>    
      <div class="row">
        <div class="col-md-12">
          <h2>See the whole ranking</h2>
        </div>
          <div class="col-md-3 col-sm-6 post">
          <%= link_to "Go to rank", players_path, class: "btn btn-default" %>
        </div>          
      </div>

app/views/players/edit.html.erb
<% provide(:title, "Edit avatar") %>
<h1>Change avatar</h1>
<p>Do you want to change avatar of <b><%= @player.full_name %>?</b></p>
<p>The current avatar is:</p>
<%= image_tag @player.avatar.url(:medium) %>
<h2>So choose a new one!</h2>
<%= form_for @player do |f| %>
  <%= f.file_field :avatar, as: :file, class: "btn btn-default" %><br>
  <%= f.submit "Change avatar", class: "btn btn-default" %>
<% end %>

app/views/players/error.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>We have the problem</h1>
    <p>
      This player doesn't exist!
    </p>
  </div>
</div>

app/views/players/index.html.erb
<% provide(:title, "Ranking") %>

<% if @players.empty? %>
  <h2>There are no players in ranking!</h2>
  <p>Try to add some players and some matches beetwen them and try again.</p>
<% else %>
  <h1>List of players</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= sortable "position" %></th>
        <th><%= sortable "nickname" %></th>
        <th>Wins/Matches</th>
        <th><%= sortable "rank" %></th>
      </tr>
    </thead>
    <tbody>
      <% @players.each do |player| %>
      <tr>
        <td class="col-md-1"><%= player.position %></td>
        <td class="col-md-2"><%= link_to player.full_name, player_path(player) %></td>
        <td class="col-md-1"><%= player.number_of_wins %> / <%= player.number_of_matches %></td>
        <td class="col-md-1"><%= player.rank %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>

app/views/players/new.html.erb
<% provide(:title, "Add new player") %>

<h1>Add new player</h1>
<div class="row">
  <div class="col-sm-4">
    <%= form_for @player do |f| %>
      <%= render '/shared/error_messages', object: f.object %>
      <%= f.label :firstname %>
      <%= f.text_field :firstname, class: 'form-control' %><br>
      <%= f.label :lastname %>
      <%= f.text_field :lastname, class: 'form-control' %><br>
      <%= f.label :nickname %>
      <%= f.text_field :nickname, class: 'form-control' %><br>
      <%= f.file_field :avatar, as: :file, class: "btn btn-default btn-file" %><br>
      <%= f.submit "Add player", class: "btn btn-default" %>
    <% end %>
  </div>
  <div class="col-sm-6">
  <%= image_tag("player.jpg") %>
  </div>
</div>

app/views/players/show.html.erb
<% provide(:title, @player.full_name) %>
    <div class="row">
      <div class="col-sm-6">
        <h2><%= @player.full_name %></h2>
        <%= image_tag @player.avatar.url(:medium) %><br><br>
        <p>This is page <b><%= @player.full_name %></b>.</p>
        <p>Here you can learn something more about him.</p>
        <p>You can change his avatar: <%= link_to "Change avatar", edit_player_path(@player), class: "btn btn-default" %></p>
      </div>
      <div class="col-sm-6">
        <h3>Statistics</h3>
        <ul class="list-group">
          <li class="list-group-item"><span class="badge"><%= @player.number_of_matches %></span> Matches</li>
          <li class="list-group-item"><span class="badge"><%= @player.number_of_wins %></span> Wins</li>
          <li class="list-group-item"><span class="badge"><%= @player.number_of_losts %></span> Losts</li>
          <li class="list-group-item"><span class="badge"><%= @player.points_earned %></span> Points earned</li>
          <li class="list-group-item"><span class="badge"><%= @player.points_lost %></span> Points lost</li>
          <li class="list-group-item"><span class="badge"><%= @player.rank %></span> Rank points:</li>
          <% if @player.position == nil %>
            <li class="list-group-item"><span class="badge">-</span> Rank position:</li>
          <% else %>
            <li class="list-group-item"><span class="badge"><%= @player.position %></span> Rank position:</li>
          <% end %>
        </ul>
      </div>
    </div>

      <div class="row">
      <% if @player.number_of_matches > 0 %>
      <div class="col-sm-6">
        <%= pie_chart({ "Wins" => @wins.count, "Losts" => @losts.count }) %>
      </div>
      <% end %>

      <% if @player.rank > 0 %>
      <div class="col-sm-6">
        <%= bar_chart({ "1st" => Player.top_player.rank, @player.nickname => @player.rank }) %>
      </div>
      <% else %>
      <div class="col-sm-6"></div>
      <% end %>
    </div>

    <div class="row">
        <div class="col-sm-6">
          <h3>Wins</h3>
          <ul class="list-group">
            <% if @player.number_of_wins > 0%>
              <% @wins.each do |match| %>
                <li class="list-group-item"><b><%= match.date %></b> with <%= Player.find(match.loser_player_id).full_name %></li>
              <% end %>
            <% else %>
              <li class="list-group-item">none</li>
            <% end %>
          </ul>
        </div>
        <div class="col-sm-6">
          <h3>Losts</h3>
          <ul class="list-group">
            <% if @player.number_of_losts > 0 %>
              <% @losts.each do |match| %>
                <li class="list-group-item"><b><%= match.date %></b> with <%= Player.find(match.winner_player_id).full_name %></li>
              <% end %>
            <% else %>
              <li class="list-group-item">none</li>
            <% end %>
          </ul>
        </div>
    </div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>